name: Deploy Staging on CloudFront
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::760615437065:role/github-action-role
          aws-region: us-east-1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install
          ng build

      - name: Copy to S3 Bucket
        run: |
          aws s3 cp ./dist/* s3://www.task-achiever.com
